# Generated by Django 5.1.7 on 2025-04-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_chat_room_alter_room_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
