# Generated by Django 5.1.7 on 2025-04-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='votecount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='votes',
            field=models.JSONField(decoder=dict),
        ),
    ]
