# Generated by Django 5.1.7 on 2025-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_room_votecount_alter_room_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='votes',
        ),
        migrations.AddField(
            model_name='room',
            name='voters',
            field=models.JSONField(default=dict),
        ),
    ]
