# Generated by Django 5.1.7 on 2025-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_room_votes_room_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='voters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
